camera:
  AeEnable: true
  ExposureTime: 75000
  analogueGain: 1
  crop:
  - 0
  - 1
  - 0
  - 1
  end_zone_part: 0.55
  enter_zone_part: 0.45
  fps: 60
  hflip: false
  horizontal: true
  resolution:
  - 640
  - 420
  vflip: true
device:
  FarmId: OfficeAgrobit
  LineId: 0
server:
  hostname: 192.168.158.59
  port: '5673'
